
name: Self-hositng

on:
  push:
    branches:
      - master
      
jobs:          
  # Publish built docs to gh-pages branch.
  autohost:
    runs-on: ubuntu-latest
    steps:
      - name: checkout new content
        uses: actions/checkout@v2

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: upload new content
          path: |
            /
            !/LICENSE.md
            !/README.md
            !/.github
    
      - name: checkout new gh-pages
        run: git clone https://github.com/SiewYan/Skeleton.siewyan.io.git --branch gh-pages --single-branch gh-pages

      - name: downloads artifact
        uses: actions/download-artifact@v2
        with:
          name: download new content to gh-pages
          path: gh-pages/
             
      - name: setup
        run: |
          cd gh-pages
          git config --local user.email "siew.yan.hoh@github.com"
          git config --local user.name "SiewYan"
          git add .
          git commit -m "Deploys website" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
           
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}